version: '3.8'

services:
  api:
    build: .
    command: api
    ports:
      - "8000:8000"
    volumes:
      - ./storage:/app/storage
    environment:
      - PYTHONPATH=/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: .
    command: frontend
    ports:
      - "8501:8501"
    volumes:
      - ./storage:/app/storage
    environment:
      - PYTHONPATH=/app
    depends_on:
      api:
        condition: service_healthy

volumes:
  storage: 